# Generated by Django 4.2.2 on 2023-08-18 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dentry_app', '0003_product_cat'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='pimage',
            field=models.ImageField(default=1, upload_to='image'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='cat',
            field=models.IntegerField(choices=[(1, 'book'), (2, 'Jewellery'), (3, 'Clothes')], default=1, verbose_name='Catagory'),
        ),
    ]
