# Generated by Django 4.2.2 on 2023-08-18 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dentry_app', '0004_product_pimage_alter_product_cat'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='pdetails',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
