# Generated by Django 4.2.2 on 2023-08-23 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dentry_app', '0006_cart'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
