# Generated by Django 4.2.2 on 2023-10-05 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dentry_app', '0009_product_pimage_a_product_pimage_b_product_pimage_c_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pimage', models.ImageField(default=True, upload_to='image')),
                ('pimage_1', models.ImageField(default=True, upload_to='images')),
                ('pimage_2', models.ImageField(default=True, upload_to='images')),
                ('pimage_3', models.ImageField(default=True, upload_to='images')),
                ('pimage_4', models.ImageField(default=True, upload_to='images')),
            ],
        ),
    ]
